data = [
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": "1011.3",
        "TEM_SEN": "26.8",
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": "1011.3",
        "UF": "CE",
        "RAD_GLO": "-1.9",
        "PTO_INS": "21.9",
        "TEM_MIN": "26.3",
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": "75",
        "PTO_MAX": "22.2",
        "VEN_DIR": "126",
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": "0",
        "PRE_MIN": "1010.7",
        "UMD_MAX": "77",
        "VEN_VEL": "2.3",
        "PTO_MIN": "21.8",
        "TEM_MAX": "26.6",
        "TEN_BAT": "12.5",
        "VEN_RAJ": "6.4",
        "TEM_CPU": "28",
        "TEM_INS": "26.3",
        "UMD_INS": "77",
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "0000"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": "1011.6",
        "TEM_SEN": "27.7",
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": "1011.6",
        "UF": "CE",
        "RAD_GLO": "-1.8",
        "PTO_INS": "22.4",
        "TEM_MIN": "25",
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": "77",
        "PTO_MAX": "22.4",
        "VEN_DIR": "144",
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": "0",
        "PRE_MIN": "1011.3",
        "UMD_MAX": "85",
        "VEN_VEL": "0.3",
        "PTO_MIN": "21.8",
        "TEM_MAX": "26.3",
        "TEN_BAT": "12.5",
        "VEN_RAJ": "6",
        "TEM_CPU": "27",
        "TEM_INS": "25.2",
        "UMD_INS": "84",
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "0100"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": "1011.5",
        "TEM_SEN": "27.3",
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": "1011.6",
        "UF": "CE",
        "RAD_GLO": "0.3",
        "PTO_INS": "22",
        "TEM_MIN": "25.2",
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": "81",
        "PTO_MAX": "22.4",
        "VEN_DIR": "166",
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": "0",
        "PRE_MIN": "1011.4",
        "UMD_MAX": "84",
        "VEN_VEL": "0.8",
        "PTO_MIN": "21.9",
        "TEM_MAX": "25.4",
        "TEN_BAT": "12.5",
        "VEN_RAJ": "3",
        "TEM_CPU": "27",
        "TEM_INS": "25.2",
        "UMD_INS": "82",
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "0200"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": "1011.2",
        "TEM_SEN": "26.1",
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": "1011.5",
        "UF": "CE",
        "RAD_GLO": "-1.8",
        "PTO_INS": "22",
        "TEM_MIN": "24.8",
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": "82",
        "PTO_MAX": "22.1",
        "VEN_DIR": "189",
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": "0",
        "PRE_MIN": "1011.2",
        "UMD_MAX": "84",
        "VEN_VEL": "1.7",
        "PTO_MIN": "21.8",
        "TEM_MAX": "25.3",
        "TEN_BAT": "12.5",
        "VEN_RAJ": "2.9",
        "TEM_CPU": "26",
        "TEM_INS": "24.8",
        "UMD_INS": "84",
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "0300"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,    
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "0400"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "0500"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "0600"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "0700"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "0800"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "0900"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "1000"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "1100"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "1200"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "1300"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "1400"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "1500"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "1600"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "1700"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "1800"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "1900"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "2000"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "2100"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "2200"
    },
    {
        "DC_NOME": "FORTALEZA",
        "PRE_INS": None,
        "TEM_SEN": None,
        "VL_LATITUDE": "-3.81583333",
        "PRE_MAX": None,
        "UF": "CE",
        "RAD_GLO": None,
        "PTO_INS": None,
        "TEM_MIN": None,
        "VL_LONGITUDE": "-38.53777777",
        "UMD_MIN": None,
        "PTO_MAX": None,
        "VEN_DIR": None,
        "DT_MEDICAO": "2022-07-15",
        "CHUVA": None,
        "PRE_MIN": None,
        "UMD_MAX": None,
        "VEN_VEL": None,
        "PTO_MIN": None,
        "TEM_MAX": None,
        "TEN_BAT": None,
        "VEN_RAJ": None,
        "TEM_CPU": None,
        "TEM_INS": None,
        "UMD_INS": None,
        "CD_ESTACAO": "A305",
        "HR_MEDICAO": "2300"
    }
]

def parse_name(name):
    hash = {
        "DT_MEDICAO": 'Date',
        "TEM_MAX": 'Tmax',
        "TEM_MIN": 'Tmin',
        "UMD_MAX": 'RHmax',
        "UMD_MIN": 'RHmin',
        "PRE_INS": 'P',
        "VEN_VEL": 'u2',
        "RAD_GLO": 'Rn',
        "CHUVA": 'PREC',
    }
    return hash.get(name)

def isfilled(data,field):
    count = 0
    for item in data:
        if data[field] is None:
            continue
        count += 1
    return count
    
def isnumber(value):
    return value.replace(".","").replace("-","",1).isnumeric()

field_count = {}
parsed_data = {}
for row in data:
    for key,value in row.items():
        name = parse_name(key)
        
        if not name:
            continue
        if value is None:
            continue
        if name == "Rn" and float(value) < 0:
            continue

        if name not in parsed_data:
            field_count[name] = 0
            if isnumber(value):
                parsed_data[name] = float(value)
            else:
                parsed_data[name] = value
                
        elif isnumber(value):
            parsed_data[name] += float(value)
        
        field_count[name] += 1

# Tira a media dos valores brutos adicionados na etapa anterior

for key, value in parsed_data.items():
    if isinstance(value,float) and key != "Rn":
        print(field_count)
        parsed_data[key] = value/field_count[key]

print(parsed_data)