# Generated by Django 3.2.9 on 2022-01-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationDatas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.CharField(max_length=15)),
                ('Time', models.IntegerField()),
                ('T', models.FloatField()),
                ('Tmax', models.FloatField()),
                ('Tmin', models.FloatField()),
                ('RH', models.FloatField()),
                ('RHmax', models.FloatField()),
                ('RHmin', models.FloatField()),
                ('PtOrvalhoinst', models.FloatField()),
                ('PtOrvalhomax', models.FloatField()),
                ('PtOrvalhomin', models.FloatField()),
                ('P', models.FloatField()),
                ('Pmax', models.FloatField()),
                ('Pmin', models.FloatField()),
                ('u2', models.FloatField()),
                ('Vdir', models.FloatField()),
                ('Vraj', models.FloatField()),
                ('Rn', models.FloatField()),
                ('PREC', models.FloatField()),
            ],
        ),
    ]
